# Theme: Tokyo Night
#include ./tokyo-night.conf
include ./catppuccin/themes/mocha.conf

# Font: JetBrains Mono
font_family	 family="JetBrains Mono"
font_size	 14.0
bold_font	 auto
italic_font	 auto
bold_italic_font auto

enable_audio_bell no

# Layout
enabled_layouts grid
#window_padding_width 10

# Background
#background #25272f
#background_opacity 1.0
#background_blur 1

# Tab Bar
#tab_bar_style powerline
#tab_powerline_style slanted
#tab_title_template "{index}. {title[title.rfind('/')+1:].replace('~', 'home').replace('peter@PeterArch:', '')}"
tab_bar_min_tabs            1
tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

# Keyboard Binds
map kitty_mod+t
map ctrl+tab
map kitty_mod+tab
map kitty_mod+q
map kitty_mod+kp_right
map kitty_mod+kp_left

